#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

export MANPAGER='nvim +Man!'
export MANWIDTH=999

# CYPRESS
export CYPRESS_INSTALL_BINARY=0

# Neovim install path
export PATH="$HOME/neovim/bin:$PATH"

# LunarVim path
export PATH=$HOME/.config/lunarvim/utils/bin:$PATH

# Cargo path
source $HOME/.cargo/env

#export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go

eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"


